<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>0.1.0</Version>
    <Company>Azul</Company>
    <Product>Azul Nexus</Product>
    <Copyright>Azul</Copyright>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
</Project>
