<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Nexus.Collectors.Sccm\Nexus.Collectors.Sccm.csproj" />
    <ProjectReference Include="..\Nexus.Collectors.ActiveDirectory\Nexus.Collectors.ActiveDirectory.csproj" />
    <ProjectReference Include="..\Nexus.Collectors.Graph\Nexus.Collectors.Graph.csproj" />
    <ProjectReference Include="..\Nexus.Collectors.Xdr\Nexus.Collectors.Xdr.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
